//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crypto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("crypto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85352416348471390761857874270384914563981951001289063588247342103891725817821
        ///7875307081248349163545209407719466769274265806798907563404953860971924066959
        ///33990873439051535937021513360060424329538136608722033314932108225191086821331
        ///85352416348471390761857874270384914563740022010844304974120080600401491813139
        ///42754094320239601079705920979357032304727652927366883302836081684210335872417
        ///53983819311638291620747370921467021779330613447403826659087898230266397684807
        ///1
        ///8535241634847139076185787427038491456374002 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string curva256 {
            get {
                return ResourceManager.GetString("curva256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38680231566299949321465229071300749261978620899543543426163604437680485201022408305978844040070251626464878022817413
        ///15554867684813091656413358613585902911207048483977294164890940430369036746383428978588543373861739726184418975920841
        ///32495673321782509013413575335333707477617301067736688560534551954117779382012603421865473812766222744417827373053831
        ///38680231566299949321465229071300749261978620899543543426158255778970641865758264160645458033809603878960981742047529
        ///1114034296898367193785577611901583376501 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string curva384 {
            get {
                return ResourceManager.GetString("curva384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9351222847435708344882406466366615250989843506410890871470738196703568553813314768241488969478040572166728315452375869124803260204661598186811571267272341
        ///2011090796563348909643561548422712317839574129210974164694676539823358293732300857359384068076706704320748938010699687591215505981444439470238431002981388
        ///7574875762666038169683978676526218379219611757081243357443609824351284565030410417067248691703164850991651502308717037810679177457404025104700001513502486
        ///93512228474357083448824064663666152509898435 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string curva512 {
            get {
                return ResourceManager.GetString("curva512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xF8BECC8F0DAECD1DA6D2CFB247C296E5295C4B1E95129A3B4C675F02B47F685D
        ///0xDD491129CADB77032E8DE24E6F1914B56F77091727FFD5782AC1BEB713888299
        ///0xA701B5D95E7B6C43389A79527183040DEF4BE0424148F9F42CA6FD07ACE1C4F5
        ///0xB0287123A21C3B9A6CAF7ACEF6005A6DA5D850A2800E34F394FF88CFE6A5019F
        ///0x847C6EA69DB5602DEA9F84BEEBF689F38EBE2212C42BFB0D0616F68715D6D8E1
        ///0xA674CCA971FAD0A9B74796BEFD728EDF92A5543949F5EC287FCCBAFCB69DCA93
        ///0xE72F65C4214CE919575B3DD87D9ED40E0152FB43A8E5FDCC88AA7D66790E82B3
        ///0xA1616EB14D01904FF388C2B24BA9337385 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Primos_256 {
            get {
                return ResourceManager.GetString("Primos_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39192838064239609572845075855742560860218018940104985173115533138993439062058927040428372708644069704384649696259253
        ///38264778324151334622487118188065599155107967624626296961519671482445849793456940407345872856977134154243559650825911
        ///26162328470445241294130660081814735874735457273870712021489643626249222799235130032653130478605910960963284421415033
        ///28289441954125951067071218202706955693762072786608895916459805354890835983354328443973986063986314048440637155186463
        ///2409064209064040284194121104064731795322 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Primos_384 {
            get {
                return ResourceManager.GetString("Primos_384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xD01977B1D2B6638DF638211AA6C2FA62A75C03751C89CC6494220ECCACBF6BE914683C62397B3FF549200E35185806D523EA26FB0F7476D82DF735B12CC76D61
        ///0x94B68047CA43CB2785457CEDC2AE555C509F13A6BDD9C9DE4B530C603A811AB72378C522F905672D176217D38B9ADBF22FC2521984FBA829B6058006E9333AD3
        ///0xAC4A5C2F6503444ACF499A34DBCBA0C225E58871681D17F3A554AD892BD88BB7D919D89E269C224A09AD10814FEE659EC94D7219FFD1D48A248F1568BB7C1F9D
        ///0xBD4C7F2E7CE7B046FB292D8E74AFAA20C786C248E9EF5C2EA6DD337FD53C791A4103F65BB3AA70A2063F65D894F180843EA856183AC20A4BEE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Primos_512 {
            get {
                return ResourceManager.GetString("Primos_512", resourceCulture);
            }
        }
    }
}
